pagopa/hub-pa-fe

proxy.conf.json
src/app/models/token-introspect-response.spec.ts
src/app/models/token-introspect-response.ts
src/app/models/user-introspect-response.spec.ts
src/app/models/user-introspect-response.ts
src/app/pages/login-spid-page/login-spid-page.component.ts
src/app/pages/login-spid-success/login-spid-success.component.ts
src/app/services/auth.service.spec.ts
src/app/services/auth.service.ts

Add backend call to retrieve fiscal code of REF-P after login.
Fiscal code of REF-P is no longer available in URL parameters after login, it is now retrieved with introspect service.
Unit test

[PTT-141] token introspect

---

src/app/pages/avvisi-page/avvisi-step1-carica-posizioni/avvisi-step1-carica-posizioni.component.ts

This PR fix a bug when save an error job
-avvisi-step1-carica-posizioni.component.ts
fix the call to save job for set the insert date in the request body

[PTT-148] fix insert date in job save

---

src/app/pages/avvisi-page/avvisi-step1-carica-posizioni/avvisi-step1-carica-posizioni.component.ts
src/app/pages/avvisi-page/avvisi-step2-stato-caricamenti/avvisi-step2-stato-caricamenti.component.html

Details button is visible only if status is not "in corso".
Fix upload multiple times files with same name.
REF-P can't download the file if status is "in corso".
Unit and integration test.

[PTT-153] bugfix visibilità pulsante dettagli

---

src/app/pages/avvisi-page/avvisi-page.component.ts

Disabled access to upload csv page if service is not configurated.
REF-P can't upload csv if service is not configurated.

[PTT-176] navigation upload csv

---

src/app/pages/aiuto-page/aiuto-page.component.html
src/app/pages/aiuto-page/aiuto-page.component.ts
src/app/pages/home-page/posizioni-home/posizioni-home.component.html
src/app/pages/home-page/posizioni-home/posizioni-home.component.ts
src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.html
src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.ts
src/environments/environment.collaudo.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Set min and max date validity for all datepickers.
Strict validation for input dates.

[PTT-188] date inputs range

---

src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.html

Modified "aggiungi rata" anchor and icon.
Better view of configure service.

[PTT-183] configure service add installment

---

src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.html

Reduced width of dates fields in configure service.
Reduced width from col-5 to col-3 and adjusted installments header.

[PTT-184] configure service dates

---

src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.html
src/styles.sass

Improved proportions and colors of installments in configure service.
Better view of installments.

[PTT-185] configure service installments

---

src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.html

Links "scopri di più" from configure service now open correct pages.
REF-P needs to access required resources.

[PTT-182] configure service discover more

---

src/app/pages/not-found-page/not-found-page.component.html
src/app/pages/not-found-page/not-found-page.component.ts
src/assets/i18n/it.json

Improved 404 not found page.
REF-P needs to ask for support or go to home easily.

[PTT-180] navigation not found page

---

README.md
src/index.html

Updated app title to Portale TARI/TEFA.
New meaningful title.

[PTT-160] navigation app title

---

src/app/components/header/header.component.html
src/app/components/header/header.component.ts
src/assets/i18n/it.json

Added confirmation logout modal.
Logout need to be confirmed to prevent accidental click.

[PTT-159] navigation logout modal

---

src/styles.sass

Secondary button text content are now correctly white on hover state.
Text content was not readable.

[PTT-157] navigation secondary buttons

---

src/app/components/footer/footer.component.html
src/app/components/footer/footer.component.ts

Privacy policy in footer now opens modal with privacy markdown.
Fixed privacy policy in footer.

[PTT-158] navigation footer privacy

---

src/app/components/header/header.component.html

Fixed go to home links in header.
Links now correctly redirect to home.

[PTT-156] navigation go to home links

---

src/app/components/header/header.component.html

Link PagoPA S.p.A. in header now redirect to https://www.pagopa.it/
Fix link destination.

[PTT-155] navigation link pagopa

---

src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.ts

Installment dates are now checked for date order.
Installments needs to be ordered by date.

[PTT-189] configure service installment dates order

---

src/app/models/payments/payment-minimal-model.ts
src/app/pages/home-page/posizioni-home/posizioni-home.component.html
src/styles.sass

Add yellow warning icon to duplicated payments in payments page.
Easy identification of duplicates.

[PTT-216] payments duplicated

---

src/app/pages/home-page/posizioni-home/posizioni-home.component.html
src/app/pages/home-page/posizioni-home/posizioni-home.component.ts
src/environments/environment.collaudo.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Add cross checks to dates range in payments page.
Better validation of filters.

[PTT-200] payments date filter

---

src/app/pages/aiuto-page/aiuto-page.component.html
src/app/pages/aiuto-page/aiuto-page.component.ts

Unified type contact and platform call dropdowns in support page.
Better view of the page.

[PTT-169] support type contact

---

src/app/pages/aiuto-page/aiuto-page.component.html

Left aligned send button of support page.
Better view of the page.

[PTT-168] support send

---

src/app/pages/aiuto-page/aiuto-page.component.html

Left aligned title of support page.
Better view of the page.

[PTT-167] support title

---

src/app/pages/login-spid-page/login-spid-page.component.html
src/assets/i18n/it.json

Removed black border.
Removed title "autenticazione".
Removed separator.
Reorganized content.
New template of SPID login page.

[PTT-172] [PTT-173] [PTT-174] [PTT-175] login spid page

---

src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.html
src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.ts

Secondary percentages (TEFA) are disabled based on installment date.
REF-P can't insert TEFA for dates before 1/7/2021

[PTT-186] configure service secondary percentages

---

src/app/components/notification/notification.component.html
src/app/services/notification.service.ts
src/styles.sass

Add timeout to notifications.
Notifications now close automatically.
Unit test and integration tests.

[PTT-191] notification

---

src/app/pages/home-page/posizioni-home/posizioni-home.component.html
src/styles.sass

Improved filters organization in payments page.
Better view of the page.

[PTT-199] payments filters

---

src/app/pages/home-page/posizioni-home/posizioni-home.component.html
src/app/pages/tributi-page/tributi-step2-definisci-rate/tributi-step2-definisci-rate.component.ts
src/styles.sass

Improved paddings and organization of payments details modal.
Better align of items in modal.
Better view of payments detail modal.

[PTT-202] [PTT-203] payments detail modal

---

src/app/pages/tributi-page/tributi-step1-imposta-enti/tributi-step1-imposta-enti.component.html
src/app/pages/tributi-page/tributi-step1-imposta-enti/tributi-step1-imposta-enti.component.ts

Fixed min and max value for secondary percentage (TEFA) to 0.01/99.99.
Updated form validator and input min/max values.
Value of 0 is not allowed.

[PTT-178] configure service min max tefa

---

src/app/pages/avvisi-page/avvisi-step2-stato-caricamenti/avvisi-step2-stato-caricamenti.component.html
src/app/pages/avvisi-page/avvisi-step2-stato-caricamenti/avvisi-step2-stato-caricamenti.component.ts
src/app/services/payments.service.ts

Add file name to request of open details button in upload status page.
Backend needs additional parameter.

[PTT-232] upload status file name

---

src/app/models/tribute.ts

Updated description in position detail modal.
New constant configuration.

[PTT-204] position detail description

---

src/environments/environment.collaudo.ts
src/environments/environment.prod.ts

Incrementated pagination items to 50 in notice payment list

[PTT-290] increment to 50 the pagination items

---

src/environments/environment.collaudo.ts
src/environments/environment.prod.ts

the csv file maximum is reduced to 200 records

[PTT-291] the csv file maximum is reduced to 200 records

---

src/app/pages/tributi-page/tributi-step1-imposta-enti/tributi-step1-imposta-enti.component.ts

Fix primary iban list in configure service page to retrieve all ibans.
Fix "seleziona un'opzione" in primary iban list.
REF-P wants to use all ibans.

[PTT-292] configure service iban primary

---

src/app/pages/home-page/posizioni-home/posizioni-home.component.html
src/styles.sass

Added colors to payments status filter modal labels.
Added bold to labels to improve visibility.
New page template.

[PTT-297] payments status filter colors

---

src/app/pages/home-page/posizioni-home/posizioni-home.component.html
src/app/pages/home-page/posizioni-home/posizioni-home.component.ts
src/environments/environment.collaudo.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Publish functionality from payments page can now be enabled/disabled by env config.
Publish will be enabled at a later date in production.

[PTT-312] payments publish enable by env

---

src/app/pages/aiuto-page/aiuto-page.component.html
src/app/pages/aiuto-page/aiuto-page.component.ts
src/app/pages/avvisi-page/avvisi-step1-carica-posizioni/avvisi-step1-carica-posizioni.component.ts
src/assets/i18n/it.json

Added description in support page.
Removed trim from fiscal code in upload csv.
New template and not necessary trim of fiscal code.
Unit and integration test.

[PTT-305] support page description, fiscal code trim

---

proxy.conf.json
src/app/pages/avvisi-page/avvisi-step2-stato-caricamenti/avvisi-step2-stato-caricamenti.component.ts
src/app/pages/home-page/posizioni-home/posizioni-home.component.ts
src/app/pages/login-spid-success/login-spid-success.component.ts
src/app/services/download.service.ts
src/app/services/ente.service.ts
src/app/services/payments.service.ts
src/assets/csv/template.csv

Fix window.open GET calls to backend to include Bearer token
Iban endpoint now has correct "/ente" prefix instead of "/pa"
Fix privacy and creditors select page after login
Updated proxy.conf for dev environment
Removed values from template csv
Receipt and export were not correct.

[PTT-331] window open

---

src/app/pages/home-page/posizioni-home/posizioni-home.component.html

Export and publish bar in payments page is now sticky to bottom of page (bootstrap affix behaviour).
Improvement of page navigation.

[PTT-323] multiple select payments

---

src/app/pages/home-page/posizioni-home/posizioni-home.component.ts

Payments filters page: current page was not updated after "goToFirstPage" (page 0 was used only for first query).
Page reset when filters change.

[PTT-349] payments filter page (new)

---

src/assets/markdown/privacy.md

This PR proposes to add a markdown representing the approved privacy policy
- New markdown of the privacy policy 
This PR is required to make the web site GDPR compliant
No tests, should be tested in UAT environment after deploy

[PTT-247] Add markdown of approved privacy policy

---

src/assets/markdown/privacy.md

This PR updates T&C file, improving the content hierarchy with proper markdown syntax.
- Improved hierarchy
Markdown preview tested on a markdown editor

[PTT-357] Update privacy.md
